<?php
/**
 *
 * Bad Bot Gatekeeper extension for the phpBB Forum Software package.
 *
 * @copyright (c) 2026 sebo, fiatpandaclub.org
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

namespace sebo\bbgatekeeper\core;

/**
* Writes store/bbgatekeeper_logger.php from the static template and wires it
* up via the document root's .user.ini.
*
* render_logger(), render_ini_line() and render_ini_full() only build
* strings in memory and never touch disk - they are reused both by the
* normal write path below and by fallback_packager (manual ZIP download
* when store/ or the document root aren't writable).
*/
class deployer
{
	/** @var string absolute path to store/, trailing slash */
	protected $store_path;

	/** @var string absolute path to the phpBB/document root, trailing slash */
	protected $root_path;

	/** @var \phpbb\request\request_interface */
	public $request;

	/** @var string last technical error, for logs - not translated, not shown to end users directly */
	protected $last_error = '';

	/**
	* @param string $store_path
	* @param string $root_path
	*/
	public function __construct(string $store_path, string $root_path, \phpbb\request\request $request)
	{
		$this->store_path = $store_path;
		$this->root_path = $root_path;
		$this->request = $request;
	}

	/**
	* @return string technical reason for the last failure, empty string
	*                if the last call succeeded
	*/
	public function get_last_error(): string
	{
		return $this->last_error;
	}

	/**
	* Full deploy cycle. config.php must already have been generated
	* separately by config_exporter::export() before calling this.
	*
	* @return bool
	*/
	public function deploy(): bool
	{
		return $this->deploy_logger();
	}

	/**
	* Copies the static logger.php template into store/bbgatekeeper_logger.php.
	*
	* @return bool
	*/
	public function deploy_logger(): bool
	{
		global $user;

		$user->add_lang_ext('sebo/bbgatekeeper', 'config_lang');

		$this->last_error = '';

		$rendered = $this->render_logger();
		if ($rendered === null)
		{
			// last_error already set by render_logger()
			return false;
		}

		if (!is_dir($this->store_path) && !@mkdir($this->store_path, 0750, true))
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_CANNOT_CREATE_STORE_DIR', $this->store_path);
			return false;
		}

		$target = $this->store_path . 'bbgatekeeper_logger.php';
		if (@file_put_contents($target, $rendered) === false)
		{
			$error = error_get_last();
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_FAILED_TO_WRITE', $target, $error['message'] ?? 'unknown error');
			return false;
		}

		@chmod($target, 0640);

		// Attempt to wire up .user.ini; failure here is non-fatal for the
		// return value of deploy_logger() since bbgatekeeper_logger.php itself
		// was already written successfully. $this->last_error is populated by
		// write_ini_line() on failure, available for the caller to inspect.
		$this->write_ini_line();

		return true;
	}

	/**
	* Renders the bbgatekeeper_logger.php content WITHOUT writing it to
	* disk. Used both by deploy_logger() and by fallback_packager when
	* store/ isn't writable.
	*
	* @return string|null null on failure - check get_last_error()
	*/
	public function render_logger(): ?string
	{
		global $user;
		$user->add_lang_ext('sebo/bbgatekeeper', 'config_lang');

		$template_path = __DIR__ . '/templates/logger.php.template';
		if (!is_readable($template_path))
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_TEMPLATE_NOT_READABLE', $template_path);
			return null;
		}

		$content = file_get_contents($template_path);
		if ($content === false)
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_FAILED_TO_READ_TEMPLATE', $template_path);
			return null;
		}

		// The template already opens with its own "<?php" tag; strip it so
		// we can prepend a generated-file header instead.
		$content = preg_replace('/^<\?php\s*/', '', $content, 1);
		$header = "<?php\n/**\n * store/bbgatekeeper_logger.php — GENERATED FILE, do not edit by hand.\n * Generated by sebo\\bbgatekeeper on " . date('c') . ".\n */\n\n";

		// English fallback
		$user->add_lang_ext('sebo/bbgatekeeper', 'template', 'en');
		// User language if exists
		$user->add_lang_ext('sebo/bbgatekeeper', 'template');

		$replacements = $this->build_logger_lang_replacements();
		$rendered = str_replace(array_keys($replacements), array_values($replacements), $content);

		return $header . $rendered;
	}

	/**
	* Translates a duration in seconds into text
	* used in the hCaptcha challenge page to show the real cookie TTL.
	*/
	protected function format_duration(int $seconds): string
	{
		global $user;

		if ($seconds < 3600)
		{
			// Less than an hour: use minutes
			$minutes = (int) round($seconds / 60);
			return $minutes . ' ' . $user->lang($minutes === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_MINUTE' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_MINUTES');
		}
		else if ($seconds < 86400)
		{
			// Less than a day: use hours
			$hours = (int) round($seconds / 3600);
			return $hours . ' ' . $user->lang($hours === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_HOUR' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_HOURS');
		}
		else if ($seconds < 604800)
		{
			// Days
			$days = (int) round($seconds / 86400);
			return $days . ' ' . $user->lang($days === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_DAY' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_DAYS');
		}
		else
		{
			// Weeks
			$days = (int) round($seconds / 604800);
			return $days . ' ' . $user->lang($days === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_WEEK' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_WEEKS');
		}
	}

	/**
	* Builds the {{PLACEHOLDER}} => resolved lang string map used to
	* render the hCaptcha challenge page embedded in logger.php.
	*
	* @return array<string, string>
	*/
	protected function build_logger_lang_replacements(): array
	{
		global $user, $config;

		$email_address = $config['board_email'];
		$email_parts = explode('@', $email_address);

		$email_user = isset($email_parts[0]) ? $email_parts[0] : '';
		$email_domain = isset($email_parts[1]) ? $email_parts[1] : '';

		// Placeholders that map to a lang key and go through $user->lang()
		$lang_map = [
			'BB_LOGGER_LANG_SECURITY_CHECK'              => 'BBGATEKEEPER_TEMPLATE_LOGGER_SECURITY_CHECK',
			'BB_LOGGER_LANG_SECURITY_CHECK_EXPLAIN'      => 'BBGATEKEEPER_TEMPLATE_LOGGER_SECURITY_CHECK_EXPLAIN',
			'BB_LOGGER_LANG_SECURITY_CHECK_COOKIE'       => 'BBGATEKEEPER_TEMPLATE_LOGGER_COOKIE',
			'BB_LOGGER_LANG_SECURITY_CHECK_CLAUSE'       => 'BBGATEKEEPER_TEMPLATE_LOGGER_CLAUSE',
			'BB_LOGGER_LANG_SECURITY_CHECK_JS'           => 'BBGATEKEEPER_TEMPLATE_LOGGER_JS',
			'BB_LOGGER_LANG_SECURITY_CHECK_DO_NOT_AGREE' => 'BBGATEKEEPER_TEMPLATE_LOGGER_DO_NOT_AGREE',
			'BB_LOGGER_LANG_TEMPLATE_ASSISTANCE'         => 'BBGATEKEEPER_TEMPLATE_LOGGER_ASSISTANCE',
			'BB_LOGGER_TEMPLATE_BUTTON'                  => 'BBGATEKEEPER_TEMPLATE_LOGGER_BUTTON',
			'BB_LOGGER_TEMPLATE_ERROR_TOO_MANY_REQUESTS' => 'BBGATEKEEPER_TEMPLATE_LOGGER_ERROR_TOO_MANY_REQUESTS',
		];

		// Placeholders that are already resolved values, no translation needed
		$raw_map = [
			'BB_LOGGER_TEMPLATE_EMAIL_NAME'   => $email_user,
			'BB_LOGGER_TEMPLATE_EMAIL_DOMAIN' => $email_domain,
			'BB_LOGGER_LANG_CONFIG'           => $user->data['user_lang'],
		];

		$replacements = [];

		foreach ($lang_map as $placeholder => $key)
		{
			if ($key === 'BBGATEKEEPER_TEMPLATE_LOGGER_CLAUSE')
			{
				$ttl = (int) ($config['bbgatekeeper_cookie_ttl'] ?? 0);
				// Pass the formatted duration to the lang string
				$value = $user->lang($key, $this->format_duration($ttl));
			}
			else
			{
				$value = $user->lang($key);
			}

			$replacements['{{' . $placeholder . '}}'] = $value;
		}

		foreach ($raw_map as $placeholder => $value)
		{
			$replacements['{{' . $placeholder . '}}'] = (string) $value;
		}

		return $replacements;
	}

	/**
	* Resolves the absolute, forward-slash path to bbgatekeeper_logger.php
	* exactly as it must appear in auto_prepend_file, against
	* DOCUMENT_ROOT / SCRIPT_FILENAME.
	*
	* @return string|null null if it cannot be resolved (e.g. missing
	*                      request server globals)
	*/
	protected function compute_prepend_path(): ?string
	{
		global $user;
		$user->add_lang_ext('sebo/bbgatekeeper', 'config_lang');

		$script_dir = dirname($this->request->server('SCRIPT_FILENAME'));

		$base_path = realpath($script_dir . '/' . $this->root_path);

		if ($base_path === false)
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_CANNOT_SOLVE_BASE_PATH');
			return null;
		}

		// Remove points: transform "./../ext/..." to "ext/..."
		$clean_store_path = preg_replace('#^(\.{1,2}/)+#', '', $this->store_path);

		$prepend_path = $base_path . '/' . $clean_store_path . 'bbgatekeeper_logger.php';

		// Normalize slashes
		return str_replace('\\', '/', $prepend_path);
	}

	/**
	* Builds the single auto_prepend_file line, without touching disk.
	*
	* @return string|null null if the path cannot be resolved
	*/
	public function render_ini_line(): ?string
	{
		$prepend_path = $this->compute_prepend_path();
		if ($prepend_path === null)
		{
			return null;
		}

		return 'auto_prepend_file = "' . $prepend_path . '"';
	}

	/**
	* Renders a full, downloadable .user.ini in memory: if the live file
	* is currently readable, its content is reused with the
	* auto_prepend_file line added/updated in place; otherwise a
	* brand-new file containing only that line is generated. Never
	* touches disk - only used to build the fallback_packager ZIP.
	*
	* IMPORTANT: the caller must always warn the admin that an existing
	* .user.ini on the server must NOT be blindly overwritten with this
	* one - only the auto_prepend_file line should be merged in, since
	* .user.ini commonly holds unrelated PHP ini directives (upload
	* limits, memory_limit, timezone, etc.) that this extension knows
	* nothing about.
	*
	* @return string|null null if the path cannot be resolved
	*/
	public function render_ini_full(): ?string
	{
		$line = $this->render_ini_line();
		if ($line === null)
		{
			return null;
		}

		$doc_root = $this->request->server('DOCUMENT_ROOT');
		$lines = [];

		if (!empty($doc_root))
		{
			$ini_path = rtrim($doc_root, '/\\') . '/.user.ini';
			if (is_readable($ini_path))
			{
				$current = @file_get_contents($ini_path);
				if ($current !== false && $current !== '')
				{
					$lines = preg_split('/\r\n|\r|\n/', rtrim($current, "\r\n"));
				}
			}
		}

		$found = false;
		foreach ($lines as $i => $existing_line)
		{
			if (preg_match('/^\s*auto_prepend_file\s*=/i', $existing_line))
			{
				$lines[$i] = $line;
				$found = true;
			}
		}

		if (!$found)
		{
			$lines[] = $line;
		}

		return implode("\n", $lines) . "\n";
	}

	/**
	* Adds or updates the auto_prepend_file line in .user.ini, preserving
	* every other line already present.
	*
	* @return bool
	*/
	public function write_ini_line(): bool
	{
		global $user;
		$user->add_lang_ext('sebo/bbgatekeeper', 'config_lang');

		$doc_root = $this->request->server('DOCUMENT_ROOT');

		if (empty($doc_root))
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_DOCUMENT_ROOT_UNAVAILABLE');
			return false;
		}

		$line = $this->render_ini_line();
		if ($line === null)
		{
			// last_error already set by render_ini_line()/compute_prepend_path()
			return false;
		}

		return $this->update_ini_file(function (array $lines) use ($line)
		{
			$found = false;
			foreach ($lines as $i => $existing_line)
			{
				if (preg_match('/^\s*auto_prepend_file\s*=/i', $existing_line))
				{
					$lines[$i] = $line;
					$found = true;
				}
			}

			if (!$found)
			{
				$lines[] = $line;
			}

			return $lines;
		});
	}

	/**
	* Reads .user.ini (treating a missing file as empty), applies a
	* transformation callback to its lines, writes the result back, then
	* re-reads it to confirm the write actually landed before the caller
	* trusts the return value.
	*
	* @param callable $transform fn(array<string> $lines): array<string>
	* @return bool
	*/
	protected function update_ini_file(callable $transform): bool
	{
		global $user;
		$user->add_lang_ext('sebo/bbgatekeeper', 'config_lang');

		$doc_root = $this->request->server('DOCUMENT_ROOT');

		if (empty($doc_root))
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_DOCUMENT_ROOT_UNAVAILABLE');
			return false;
		}

		$ini_path = rtrim($doc_root, '/\\') . '/.user.ini';

		// If the file doesn't exist, start from an empty array
		if (!file_exists($ini_path))
		{
			$lines = [];
		}
		else
		{
			$current = @file_get_contents($ini_path);
			if ($current === false)
			{
				$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_CANNOT_READ_INI', $ini_path);
				return false;
			}
			$lines = ($current === '') ? [] : preg_split('/\r\n|\r|\n/', rtrim($current, "\r\n"));
		}

		$new_lines = $transform($lines);
		$new_content = implode("\n", $new_lines) . "\n";

		if (@file_put_contents($ini_path, $new_content) === false)
		{
			$error = error_get_last();
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_FAILED_TO_WRITE', $ini_path, $error['message'] ?? 'unknown error');
			return false;
		}

		clearstatcache(true, $ini_path);
		$verify = @file_get_contents($ini_path);

		if ($verify !== $new_content)
		{
			$this->last_error = $user->lang('BBGATEKEEPER_CONFIG_WRITE_VERIFICATION_FAIL_INI', $ini_path);
			return false;
		}

		return true;
	}

	/**
	* Removes the auto_prepend_file line from .user.ini, leaving every
	* other line untouched. See core/reset.php for the required ordering
	* relative to deleting store/.
	*
	* @return bool
	*/
	public function remove_ini_line(): bool
	{
		return $this->update_ini_file(function (array $lines)
		{
			return array_values(array_filter($lines, function ($existing_line)
			{
				return !preg_match('/^\s*auto_prepend_file\s*=/i', $existing_line);
			}));
		});
	}
}
