<?php
/**
 *
 * Bad Bot Gatekeeper extension for the phpBB Forum Software package.
 *
 * @copyright (c) 2026 sebo, fiatpandaclub.org
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

namespace sebo\bbgatekeeper\core;

/**
* Writes store/bbgatekeeper_logger.php from the static template and wires it
* up via the document root's .user.ini.
*/
class deployer
{
	/** @var string absolute path to store/, trailing slash */
	protected $store_path;

	/** @var string absolute path to the phpBB/document root, trailing slash */
	protected $root_path;

	/** @var \phpbb\request\request_interface */
	public $request;

	/**
	* @param string $store_path
	* @param string $root_path
	*/
	public function __construct(string $store_path, string $root_path, \phpbb\request\request $request)
	{
		$this->store_path = $store_path;
		$this->root_path = $root_path;
		$this->request = $request;
	}

	/**
	* Full deploy cycle. config.php must already have been generated
	* separately by config_exporter::export() before calling this.
	*
	* @return bool
	*/
	public function deploy(): bool
	{
		return $this->deploy_logger();
	}

	/**
	* Copies the static logger.php template into store/bbgatekeeper_logger.php.
	*
	* @return bool
	*/
	public function deploy_logger(): bool
	{
		global $user;
		
		$template_path = __DIR__ . '/templates/logger.php.template';
		if (!is_readable($template_path))
		{
			return false;
		}

		$content = file_get_contents($template_path);
		if ($content === false)
		{
			return false;
		}

		// The template already opens with its own "<?php" tag; strip it so
		// we can prepend a generated-file header instead.
		$content = preg_replace('/^<\?php\s*/', '', $content, 1);
		$header = "<?php\n/**\n * store/bbgatekeeper_logger.php — GENERATED FILE, do not edit by hand.\n * Generated by sebo\\bbgatekeeper on " . date('c') . ".\n */\n\n";

		if (!is_dir($this->store_path) && !@mkdir($this->store_path, 0750, true))
		{
			return false;
		}
		// English fallback
		$user->add_lang_ext('sebo/bbgatekeeper', 'template', 'en');
		// User language if exists
		$user->add_lang_ext('sebo/bbgatekeeper', 'template');

		$replacements = $this->build_logger_lang_replacements();
		$rendered = str_replace(array_keys($replacements), array_values($replacements), $content);

		$target = $this->store_path . 'bbgatekeeper_logger.php';
		if (@file_put_contents($target, $header . $rendered) === false)
		{
			return false;
		}

		@chmod($target, 0640);

		if (!$this->write_ini_line())
		{
			trigger_error('LOG_BBGATEKEEPER_INI_UPDATE_FAILED');
		}

		return true;
	}

	/**
	* Translates a duration in seconds into text 
	* used in the hCaptcha challenge page to show the real cookie TTL.
	*/
	protected function format_duration(int $seconds): string
	{
		global $user;

		if ($seconds < 3600)
		{
			// Less than an hour: use minutes
			$minutes = (int) round($seconds / 60);
			return $minutes . ' ' . $user->lang($minutes === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_MINUTE' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_MINUTES');
		}
		else if ($seconds < 86400)
		{
			// Less than a day: use hours
			$hours = (int) round($seconds / 3600);
			return $hours . ' ' . $user->lang($hours === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_HOUR' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_HOURS');
		}
		else if ($seconds < 604800)
		{
			// Days
			$days = (int) round($seconds / 86400);
			return $days . ' ' . $user->lang($days === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_DAY' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_DAYS');
		}
		else
		{
			// Weeks
			$days = (int) round($seconds / 604800);
			return $days . ' ' . $user->lang($days === 1 ? 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_WEEK' : 'BBGATEKEEPER_TEMPLATE_LOGGER_WORD_WEEKS');
		}
	}

	/**
	* Builds the {{PLACEHOLDER}} => safe PHP literal map. Every value goes
	* through var_export(), so quoting/escaping is handled correctly
	* regardless of content.
	*
	* @return array<string, string>
	*/
	/**
	 * Translates a duration in seconds into text 
	 * used in the hCaptcha challenge page to show the real cookie TTL.
	 */
	protected function build_logger_lang_replacements(): array
	{
		global $user, $config;

		$email_address = $config['board_email'];
		$email_parts = explode('@', $email_address);

		$email_user = isset($email_parts[0]) ? $email_parts[0] : '';
		$email_domain = isset($email_parts[1]) ? $email_parts[1] : '';

		$lang_map = [
			'BB_LOGGER_SITE_KEY_FOR_HTML' 				=> null,
			'BB_LOGGER_LANG_SECURITY_CHECK' 			=> 'BBGATEKEEPER_TEMPLATE_LOGGER_SECURITY_CHECK',
			'BB_LOGGER_LANG_SECURITY_CHECK_EXPLAIN' 	=> 'BBGATEKEEPER_TEMPLATE_LOGGER_SECURITY_CHECK_EXPLAIN',
			'BB_LOGGER_LANG_SECURITY_CHECK_COOKIE' 		=> 'BBGATEKEEPER_TEMPLATE_LOGGER_COOKIE',
			'BB_LOGGER_LANG_SECURITY_CHECK_CLAUSE' 		=> 'BBGATEKEEPER_TEMPLATE_LOGGER_CLAUSE',
			'BB_LOGGER_LANG_SECURITY_CHECK_JS' 			=> 'BBGATEKEEPER_TEMPLATE_LOGGER_JS',
			'BB_LOGGER_LANG_SECURITY_CHECK_DO_NOT_AGREE' => 'BBGATEKEEPER_TEMPLATE_LOGGER_DO_NOT_AGREE',
			'BB_LOGGER_LANG_TEMPLATE_ASSISTANCE' 		=> 'BBGATEKEEPER_TEMPLATE_LOGGER_ASSISTANCE',
			'BB_LOGGER_TEMPLATE_BUTTON' 				=> 'BBGATEKEEPER_TEMPLATE_LOGGER_BUTTON',
			'BB_LOGGER_TEMPLATE_ERROR_TOO_MANY_REQUESTS' => 'BBGATEKEEPER_TEMPLATE_LOGGER_ERROR_TOO_MANY_REQUESTS',
			'BB_LOGGER_TEMPLATE_EMAIL_NAME' 			=> $email_user,
			'BB_LOGGER_TEMPLATE_EMAIL_DOMAIN' 			=> $email_domain,
		];

		$replacements = [];
		foreach ($lang_map as $placeholder => $key)
		{
			if ($placeholder === 'BB_LOGGER_SITE_KEY_FOR_HTML')
			{
				$value = (string) $config['bbgatekeeper_hcap_site_key'];
			}
			else if ($placeholder === 'BB_LOGGER_TEMPLATE_EMAIL_NAME' || $placeholder === 'BB_LOGGER_TEMPLATE_EMAIL_DOMAIN')
			{
				$value = (string) $key;
			}
			else if ($key === 'BBGATEKEEPER_TEMPLATE_LOGGER_CLAUSE')
			{
				$ttl = (int) ($config['bbgatekeeper_cookie_ttl'] ?? 0);
				// Pass the formatted duration to the lang string
				$value = $user->lang($key, $this->format_duration($ttl));
			}
			else
			{
				$value = $user->lang($key);
			}

			$replacements['{{' . $placeholder . '}}'] = $value;
		}

		return $replacements;
	}

	/**
	* Adds or updates the auto_prepend_file line in .user.ini, preserving
	* every other line already present.
	*
	* @return bool
	*/
	public function write_ini_line(): bool
	{
		$doc_root = $this->request->server('DOCUMENT_ROOT');
        
        if (empty($doc_root))
        {
            return false;
        }
        
		$ini_path = rtrim($doc_root, '/\\') . '/.user.ini';

        // make the dir to check
        $script_dir = dirname($this->request->server('SCRIPT_FILENAME'));
        
        $base_path = realpath($script_dir . '/' . $this->root_path);
		
		if ($base_path === false)
        {
            return false;
        }

        $clean_store_path = preg_replace('#^(\.{1,2}/)+#', '', $this->store_path);
		$prepend_path = $base_path . '/' . $clean_store_path . 'bbgatekeeper_logger.php';   
		$prepend_path = str_replace('\\', '/', $prepend_path);	
		
		$line = 'auto_prepend_file = "' . $prepend_path . '"';

		return $this->update_ini_file(function (array $lines) use ($line)
		{
			$found = false;
			foreach ($lines as $i => $existing_line)
			{
				if (preg_match('/^\s*auto_prepend_file\s*=/i', $existing_line))
				{
					$lines[$i] = $line;
					$found = true;
				}
			}

			if (!$found)
			{
				$lines[] = $line;
			}

			return $lines;
		});
	}

	/**
	* Reads .user.ini (treating a missing file as empty), applies a
	* transformation callback to its lines, writes the result back, then
	* re-reads it to confirm the write actually landed before the caller
	* trusts the return value.
	*
	* @param callable $transform fn(array<string> $lines): array<string>
	* @return bool
	*/
	protected function update_ini_file(callable $transform): bool
	{
		$doc_root = $this->request->server('DOCUMENT_ROOT');
		
		if (empty($doc_root))
		{
			return false;
		}
		
		$ini_path = rtrim($doc_root, '/\\') . '/.user.ini';

		// Se il file non esiste, iniziamo con un array vuoto
		if (!file_exists($ini_path))
		{
			$lines = [];
		}
		else
		{
			$current = @file_get_contents($ini_path);
			if ($current === false)
			{
				return false;
			}
			$lines = ($current === '') ? [] : preg_split('/\r\n|\r|\n/', rtrim($current, "\r\n"));
		}

		$new_lines = $transform($lines);
		$new_content = implode("\n", $new_lines) . "\n";

		if (@file_put_contents($ini_path, $new_content) === false)
		{
			return false;
		}

		clearstatcache(true, $ini_path);
		$verify = @file_get_contents($ini_path);

		return $verify === $new_content;
	}

	/**
	* Removes the auto_prepend_file line from .user.ini, leaving every
	* other line untouched. See core/reset.php for the required ordering
	* relative to deleting store/.
	*
	* @return bool
	*/
	public function remove_ini_line(): bool
	{
		return $this->update_ini_file(function (array $lines)
		{
			return array_values(array_filter($lines, function ($existing_line)
			{
				return !preg_match('/^\s*auto_prepend_file\s*=/i', $existing_line);
			}));
		});
	}
}